name: Build artifacts

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.x
        uses: actions/setup-go@v2
        with:
          go-version: '1.17.2'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2

      - name: Run build-artifacts command
        run: make ci-build-artifacts

      - uses: actions/upload-artifact@v2
        with:
          path: soracom/dist/ghactions/
